# -*- coding: utf-8 -*-
"""Lab1OfficalData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReCjl9AKhdiZAAqiTZtfWbEF3rIiNXDu
"""

import numpy as np
import matplotlib.pyplot as plt

with open('Test8_3.9V_13.6mA', 'r') as f:
    for i in range(10):
        print(f.readline())

    data = np.loadtxt('Test8_3.9V_13.6mA', skiprows=1) # this is at room temp with no voltage added

# Separate the columns
voltage = data[:, 0]      # applied voltage
current = data[:, 1]      # measured current

# Plot
plt.figure(figsize=(10, 6))

plt.plot(voltage, current)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Measured Current')
plt.title('Current vs Applied Voltage - Test 8')

plt.grid(True)
plt.show()


data = np.loadtxt('Test8_3.9V_13.6mA', skiprows=1)

voltage = data[:, 0]
current = data[:, 1]

# Remove the initial offset
current_change = current - current[0]

plt.figure(figsize=(10,6))
plt.plot(voltage, current_change)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Change in Measured Current')
plt.title('Test 8 - Current Change vs Applied Voltage')
plt.grid(True)

plt.show()

with open('Test7_3.9V_13.5mA', 'r') as f:
    for i in range(10):
        print(f.readline())

    data = np.loadtxt('Test7_3.9V_13.5mA', skiprows=1) # this is at room temp with no voltage added

# Separate the columns
voltage = data[:, 0]      # applied voltage
current = data[:, 1]      # measured current

# Plot
plt.figure(figsize=(10, 6))

plt.plot(voltage, current)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Measured Current')
plt.title('Current vs Applied Voltage - Test 7')

plt.grid(True)
plt.show()

with open('Test6_3.9V_13.8mA', 'r') as f:
    for i in range(10):
        print(f.readline())

    data = np.loadtxt('Test6_3.9V_13.8mA', skiprows=1) # this is at room temp with no voltage added

# Separate the columns
voltage = data[:, 0]      # applied voltage
current = data[:, 1]      # measured current

# Plot
plt.figure(figsize=(10, 6))

plt.plot(voltage, current)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Measured Current')
plt.title('Current vs Applied Voltage - Test 6')

plt.grid(True)
plt.show()

with open('Test5_3.9V_13.8mA', 'r') as f:
    for i in range(10):
        print(f.readline())

    data = np.loadtxt('Test5_3.9V_13.8mA', skiprows=1) # this is at room temp with no voltage added

# Separate the columns
voltage = data[:, 0]      # applied voltage
current = data[:, 1]      # measured current

# Plot
plt.figure(figsize=(10, 6))

plt.plot(voltage, current)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Measured Current')
plt.title('Current vs Applied Voltage - Test 5')

plt.grid(True)
plt.show()

with open('Test4_REDONE', 'r') as f:
    for i in range(10):
        print(f.readline())

    data = np.loadtxt('Test4_REDONE', skiprows=1) # this is at room temp with no voltage added

# Separate the columns
voltage = data[:, 0]      # applied voltage
current = data[:, 1]      # measured current

# Plot
plt.figure(figsize=(10, 6))

plt.plot(voltage, current)

plt.xlabel('Applied Voltage (V)')
plt.ylabel('Measured Current')
plt.title('Current vs Applied Voltage - Test 4')

plt.grid(True)
plt.show()

files = [
    'Test4_REDONE',
    'Test5_3.9V_13.8mA',
    'Test6_3.9V_13.8mA',
    'Test7_3.9V_13.5mA',
    'Test8_3.9V_13.6mA'
]

temperatures = [
    '29.6°C',
    '32.7°C',
    '47.6°C',
    '64.8°C',
    '72.6°C'
]

plt.figure(figsize=(11, 7))

all_currents = []

for filename, temp in zip(files, temperatures):

    data = np.loadtxt(filename, skiprows=1)

    voltage = data[:, 0]
    current = data[:, 1]

    # Only show the voltage region we care about
    mask = (voltage >= 0.50) & (voltage <= 0.80)

    voltage = voltage[mask]
    current = current[mask]

    all_currents.extend(current)

    plt.plot(
        voltage,
        current,
        linewidth=2.5,
        label=temp
    )

# ----- ZOOM -----

plt.xlim(0.52, 0.78)

# Automatically zoom Y around these runs
ymin = min(all_currents)
ymax = max(all_currents)

padding = 0.05 * (ymax - ymin)

plt.ylim(ymin - padding, ymax + padding)

# ----- LABELS -----

plt.xlabel('Base Emitter Voltage, $V_{BE}$ (V)', fontsize=13)
plt.ylabel('Collector Current, $I_C$', fontsize=13)

plt.title(
    'Collector Current vs. Base Emitter Voltage\n'
    'at Different Transistor Temperatures',
    fontsize=14
)

plt.legend(title='Temperature', fontsize=10)
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

files = {
    29.6: 'Test4_REDONE',
    32.7: 'Test5_3.9V_13.8mA',
    47.6: 'Test6_3.9V_13.8mA',
    64.8: 'Test7_3.9V_13.5mA',
    72.6: 'Test8_3.9V_13.6mA'
}

# Approximate transition regions from YOUR graph
fit_ranges = {
    29.6: (0.725, 0.745),
    32.7: (0.695, 0.715),
    47.6: (0.670, 0.690),
    64.8: (0.645, 0.665),
    72.6: (0.630, 0.650)
}

plt.figure(figsize=(10,7))

for T, filename in files.items():

    data = np.loadtxt(filename, skiprows=1)

    V = data[:,0]
    Iraw = data[:,1]

    # Baseline from low-voltage portion
    baseline = np.median(Iraw[(V >= 0.53) & (V <= 0.60)])

    # Your measured current becomes LESS negative as
    # transistor current increases
    I = Iraw - baseline

    # Select ONLY transition region
    Vmin, Vmax = fit_ranges[T]

    mask = (
        (V >= Vmin) &
        (V <= Vmax) &
        (I > 0)
    )

    Vfit = V[mask]
    Ifit = I[mask]

    lnI = np.log(Ifit)

    # Plot actual points
    plt.scatter(
        Vfit,
        lnI,
        label=f'{T:.1f}°C'
    )

    # Linear fit
    if len(Vfit) >= 2:

        m, b = np.polyfit(Vfit, lnI, 1)

        xline = np.linspace(Vfit.min(), Vfit.max(), 100)

        plt.plot(
            xline,
            m*xline + b,
            '--'
        )

        print(
            f'{T:.1f}°C: '
            f'slope = {m:.3f} 1/V'
        )

plt.xlabel(r'Base-Emitter Voltage, $V_{BE}$ (V)')
plt.ylabel(r'$\ln(I_C)$')

plt.title(
    r'$\ln(I_C)$ vs. $V_{BE}$ in the Exponential Region'
)

plt.legend(title='Temperature')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Keep ONLY the exponential/rising region
# Exclude the plateau near ln(Ic) ~ 11.6

mask = (
    (V >= Vmin) &
    (V <= Vmax) &
    (I > 0)
)

Vfit = V[mask]
lnI = np.log(I[mask])

# Remove saturated/plateau points
linear_mask = lnI < 11.3

Vfit = Vfit[linear_mask]
lnI = lnI[linear_mask]

# Linear regression
m, b = np.polyfit(Vfit, lnI, 1)

print(f"{T:.1f} °C: slope = {m:.3f} 1/V")

# Plot data used in fit
plt.scatter(Vfit, lnI, label=f"{T:.1f}°C")

# Plot fit ONLY over fitted region
xfit = np.linspace(Vfit.min(), Vfit.max(), 100)
plt.plot(xfit, m*xfit + b, '--')

